version: '3'
services:
  jellyfin-dev:
    build: .
    ports:
      - 8096:8096
    volumes:
      - jellyfin_config:/config
      - jellyfin_media:/media
    restart: unless-stopped

volumes:
  jellyfin_config:
  jellyfin_media:
